version: '3.9'

services:
  app:
    container_name: funbase
    build: .
    depends_on:
      - db    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload 
    ports:
      - 8080:8080
    volumes:
      - .:/app

  db:
    image: postgres
    container_name: funbase_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    container_name: funbase_admin
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgAdmin:/var/lib/pgadmin
      
volumes:
  postgres:
  pgAdmin: